# Routes
get_user:
  path: /users/{uid}
  controller: App\Controller\GetUserController
  methods: [GET]

put_user:
  path: /users/{uid}
  controller: App\Controller\PutUserController
  methods: [PUT]

user_delete:
  path: /users/{id}
  controller: App\Controller\DeleteUserController
  methods: [DELETE]