parameters:
    kernel.secret: yoursecretshouldbehere
    app_path: "../.."

framework:
    form: false
    assets: false
    session: false
    translator: false
    php_errors:
        log: false

command_bus:
    command_bus:
        middlewares:
            - App\Domain\Middleware\CheckUserNameLength

dbal:
    connections:
        main:
            driver: mysql
            host: 127.0.0.1
            port: 3306
            user: root
            password: root
            dbname: users


# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    #
    # Controllers
    #
    App\Controller\:
        resource : "%app_path%/src/Controller/*"
        tags:
            - {name: controller.service_arguments}

    #
    # Repositories
    #
    App\Domain\Repository\:
        resource: "%app_path%/src/Domain/Repository/*"
        tags:
            - {name: "repository"}

    #
    # QueryHandlers
    #
    App\Domain\QueryHandler\:
        resource: "%app_path%/src/Domain/QueryHandler/*"
        tags:
            - {name: "query_handler"}

    #
    # CommandHandlers
    #
    App\Domain\CommandHandler\:
        resource: "%app_path%/src/Domain/CommandHandler/*"
        tags:
            - {name: "command_handler"}

    #
    # Services
    #
    App\Domain\Middleware\:
        resource: "%app_path%/src/Domain/Middleware/*"
        tags:
            - {name: "service"}

    App\Domain\Model\User\MemoryUserRepository:
    App\Infrastructure\DBAL\Model\User\DBALUserRepository:

    App\Domain\Model\User\UserRepository:
        alias: App\Infrastructure\DBAL\Model\User\DBALUserRepository

